version: 2.1

jobs:
  build:
    docker:
    - image: mathcomp/mathcomp:1.11.0-coq-8.11
    steps:
    - checkout
    - run:
        name: Install finmap
        command: |
          eval $(opam config env)
          opam install -y coq-mathcomp-finmap
    - run:
        name: Install Paco
        command: |
          eval $(opam config env)
          opam install -y coq-paco
    - run:
        name: Compile
        command: |
          eval $(opam config env)
          ./generateMakefile && make

